version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-resolver}

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-myredispassword}

  data-provider:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    container_name: data-provider
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-myredispassword}
    depends_on:
      - postgres
      - redis